//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pack_My_Game.IHM {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pack_My_Game.IHM.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose the CheatCodes Path.
        /// </summary>
        internal static string Choose_CCodesPath {
            get {
                return ResourceManager.GetString("Choose_CCodesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose the LaunchBox path.
        /// </summary>
        internal static string Choose_LBPath {
            get {
                return ResourceManager.GetString("Choose_LBPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compress the workfolder for this game ?.
        /// </summary>
        internal static string Compress_Question {
            get {
                return ResourceManager.GetString("Compress_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation of folder.
        /// </summary>
        internal static string CreationFolder {
            get {
                return ResourceManager.GetString("CreationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #Crédits, Thanks to:
        ///  - My little girl, waiting his dad finish his roms pack... to permit her discover my teenage.
        ///  - My ex-wife who squat my house (it&apos;s convenient) :D.
        ///
        ///  - DotNetZip author, a very good job, useful !
        ///
        ///
        ///
        ///				Sincerely.
        ///
        ///				 A.Codoul aka Daerlnaxe/Axenn.
        /// </summary>
        internal static string Credits_Content {
            get {
                return ResourceManager.GetString("Credits_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erase.
        /// </summary>
        internal static string Erase {
            get {
                return ResourceManager.GetString("Erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Would you want to ERASE the temp folder.
        /// </summary>
        internal static string EraseTmpFolder {
            get {
                return ResourceManager.GetString("EraseTmpFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à from the list.
        /// </summary>
        internal static string From_List {
            get {
                return ResourceManager.GetString("From_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Game selected.
        /// </summary>
        internal static string GameSelected {
            get {
                return ResourceManager.GetString("GameSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Step to the left, step to the righ, clap your hands....
        ///
        ///Ok... sorry... 
        ///This is a basic version English/French to help you. I&apos;m not very good in Englis, so my apologizes.
        ///
        ///What it do:
        ///  - Get ONE rom, relative pictures, xml datas to construct a zip with everything. 
        ///  - Warning, it will not the same structure but one i think to be more easy, to the unzip.
        ///  - No, it not alterate in any case your datas, roms, etc.
        ///  - It must permit to transmit this packs for the future.
        ///
        ///#1: Go to modify setting [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Help_Content {
            get {
                return ResourceManager.GetString("Help_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no verification implemented for the images copy, would you want to overwrite them.
        /// </summary>
        internal static string ImagesP {
            get {
                return ResourceManager.GetString("ImagesP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy images.
        /// </summary>
        internal static string ImagesTitle {
            get {
                return ResourceManager.GetString("ImagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Path.
        /// </summary>
        internal static string Invalid_Path {
            get {
                return ResourceManager.GetString("Invalid_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leave.
        /// </summary>
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pack this Game.
        /// </summary>
        internal static string MB_Pack_Question {
            get {
                return ResourceManager.GetString("MB_Pack_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This folder does not contain the file.
        /// </summary>
        internal static string NC_File {
            get {
                return ResourceManager.GetString("NC_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a Work folder.
        /// </summary>
        internal static string OutputBrowserDescription {
            get {
                return ResourceManager.GetString("OutputBrowserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove the game (Visual only).
        /// </summary>
        internal static string Remove_Game {
            get {
                return ResourceManager.GetString("Remove_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove.
        /// </summary>
        internal static string Remove_Word {
            get {
                return ResourceManager.GetString("Remove_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a Platform.
        /// </summary>
        internal static string SelectASystem {
            get {
                return ResourceManager.GetString("SelectASystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Platform selected.
        /// </summary>
        internal static string SystemSelected {
            get {
                return ResourceManager.GetString("SystemSelected", resourceCulture);
            }
        }
    }
}
